spring:
  application:
    name: demo

sonar:
  host:
    url: http://localhost:9000
  token: ${SONAR_TOKEN:sqa_f6b3dbba3594962684af5eccd7edc7f1032b5688}

groq:
  api-key: ${GROQ_API_KEY:YOUR_GROQ_API_KEY}
  model: llama-3.3-70b-versatile

ollama:
  api:
    url: http://localhost:11434/v1/chat/completions
  model: codellama:7b

github:
  token: ${GITHUB_TOKEN}
